version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./client
    ports:
      - 80:80
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]  
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./server
    ports:
      - 8080:8080
    env_file: ./.env
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}>
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"] 
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.36
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_USER}
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] 
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE 
